### PR TITLE
Frontend for staging area.

### LINKED ISSUE #85: Tarea 32: Add Frontend for Staging Area - Staging Area
Work item:
>  Staging Area

Description:
>  - Create staging area screen
>  - Add button to save to staging area
>  - Add button to acces datasets in staging area

### PR DESCRIPTION
**Pull request by JaviGarcia1**
### **PR Type**
Enhancement, Bug fix

___

### **Description**
- Added new dataset update functionality allowing users to modify title, description, and tags
- Fixed staging area dropzone positioning and styling for better file upload experience
- Improved error handling and user feedback for dataset operations
- Enhanced file management interface with better delete and view options
- Fixed merge conflicts and code formatting issues
- Added proper response formatting for API endpoints

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>routes.py</strong><dd><code>Dataset update and publication functionality improvements</code></dd></summary>
<hr>

app/modules/dataset/routes.py

<li>Added new route '/dataset/update' for handling dataset updates<br> <li> Fixed dataset publication and saving changes functionality<br> <li> Improved error handling and response formatting<br> <li> Added proper merge conflict resolution<br>

</details>

  </td>
  <td><a href="https://github.com/davidgonmar/uvlhub-egc/pull/187/files#diff-eae06d42747f4b8c6533d8ca1550e75c045ba215402980aac2fe13496dfce454">+173/-26</a></td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>staging_area_dataset.html</strong><dd><code>Staging area UI improvements and file management</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

app/modules/dataset/templates/dataset/staging_area_dataset.html

<li>Improved dropzone styling and positioning for file uploads<br> <li> Enhanced file list display and management interface<br> <li> Added proper form handling for dataset updates<br> <li> Fixed file deletion functionality<br>

</details>

  </td>
  <td><a href="https://github.com/davidgonmar/uvlhub-egc/pull/187/files#diff-e1109b717b16d0217eae3eca2ef8c0280efe43f47fc5ec90775a64dba6753a03">+224/-174</a></td>

</tr>
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

Closes #85

### CODE REVIEW

**Comment by davidgonmar** [comment]
## Test Coverage Report
  **conftest.py**: 100%

### **auth**
  **forms.py**: 100%
  **models.py**: 88.6800%
  **repositories.py**: 84.3100%
  **routes.py**: 53.7800%
  **services.py**: 71.1100%

### **chatbot**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 48.00%
  **services.py**: 85.7100%

### **dataset**
  **api.py**: 100%
  **forms.py**: 78.00%
  **models.py**: 78.5200%
  **repositories.py**: 80.0%
  **routes.py**: 41.0400%
  **services.py**: 55.2600%

### **explore**
  **forms.py**: 100%
  **repositories.py**: 13.2700%
  **routes.py**: 77.7800%
  **services.py**: 100%

### **fakenodo**
  **forms.py**: 0%
  **models.py**: 70.0%
  **repositories.py**: 53.8500%
  **routes.py**: 35.2300%
  **services.py**: 42.4200%

### **featuremodel**
  **forms.py**: 0%
  **models.py**: 77.1900%
  **repositories.py**: 71.4300%
  **routes.py**: 55.5600%
  **services.py**: 85.7100%

### **flamapy**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 0%
  **routes.py**: 31.9400%
  **services.py**: 0%

### **hubfile**
  **forms.py**: 0%
  **models.py**: 73.9100%
  **repositories.py**: 92.3100%
  **routes.py**: 32.2600%
  **services.py**: 72.4100%

### **notepad**
  **forms.py**: 100%
  **models.py**: 88.8900%
  **repositories.py**: 100%
  **routes.py**: 84.2100%
  **services.py**: 100%

### **profile**
  **forms.py**: 100%
  **models.py**: 76.9200%
  **repositories.py**: 100%
  **routes.py**: 76.6700%
  **services.py**: 100%

### **public**
  **routes.py**: 95.4500%

### **team**
  **routes.py**: 80.0%

### **webhook**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 0%
  **services.py**: 0%

### **zenodo**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 70.0%
  **services.py**: 35.8500%

**Comment by davidgonmar** [comment]
## Test Coverage Report
  **conftest.py**: 100%

### **auth**
  **forms.py**: 100%
  **models.py**: 88.6800%
  **repositories.py**: 84.3100%
  **routes.py**: 53.7800%
  **services.py**: 71.1100%

### **chatbot**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 48.00%
  **services.py**: 85.7100%

### **dataset**
  **api.py**: 100%
  **forms.py**: 78.00%
  **models.py**: 78.5200%
  **repositories.py**: 80.0%
  **routes.py**: 38.7400%
  **services.py**: 55.2600%

### **explore**
  **forms.py**: 100%
  **repositories.py**: 13.2700%
  **routes.py**: 77.7800%
  **services.py**: 100%

### **fakenodo**
  **forms.py**: 0%
  **models.py**: 70.0%
  **repositories.py**: 53.8500%
  **routes.py**: 35.2300%
  **services.py**: 42.4200%

### **featuremodel**
  **forms.py**: 0%
  **models.py**: 77.1900%
  **repositories.py**: 71.4300%
  **routes.py**: 55.5600%
  **services.py**: 85.7100%

### **flamapy**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 0%
  **routes.py**: 31.9400%
  **services.py**: 0%

### **hubfile**
  **forms.py**: 0%
  **models.py**: 73.9100%
  **repositories.py**: 92.3100%
  **routes.py**: 32.2600%
  **services.py**: 72.4100%

### **notepad**
  **forms.py**: 100%
  **models.py**: 88.8900%
  **repositories.py**: 100%
  **routes.py**: 84.2100%
  **services.py**: 100%

### **profile**
  **forms.py**: 100%
  **models.py**: 76.9200%
  **repositories.py**: 100%
  **routes.py**: 76.6700%
  **services.py**: 100%

### **public**
  **routes.py**: 95.4500%

### **team**
  **routes.py**: 80.0%

### **webhook**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 0%
  **services.py**: 0%

### **zenodo**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 70.0%
  **services.py**: 35.8500%

**Comment by davidgonmar** [comment]
## Test Coverage Report
  **conftest.py**: 100%

### **auth**
  **forms.py**: 100%
  **models.py**: 88.6800%
  **repositories.py**: 84.3100%
  **routes.py**: 53.7800%
  **services.py**: 71.1100%

### **chatbot**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 48.00%
  **services.py**: 85.7100%

### **dataset**
  **api.py**: 100%
  **forms.py**: 78.00%
  **models.py**: 78.5200%
  **repositories.py**: 80.0%
  **routes.py**: 38.7400%
  **services.py**: 55.2600%

### **explore**
  **forms.py**: 100%
  **repositories.py**: 13.2700%
  **routes.py**: 77.7800%
  **services.py**: 100%

### **fakenodo**
  **forms.py**: 0%
  **models.py**: 70.0%
  **repositories.py**: 53.8500%
  **routes.py**: 35.2300%
  **services.py**: 42.4200%

### **featuremodel**
  **forms.py**: 0%
  **models.py**: 77.1900%
  **repositories.py**: 71.4300%
  **routes.py**: 55.5600%
  **services.py**: 85.7100%

### **flamapy**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 0%
  **routes.py**: 31.9400%
  **services.py**: 0%

### **hubfile**
  **forms.py**: 0%
  **models.py**: 73.9100%
  **repositories.py**: 92.3100%
  **routes.py**: 32.2600%
  **services.py**: 72.4100%

### **notepad**
  **forms.py**: 100%
  **models.py**: 88.8900%
  **repositories.py**: 100%
  **routes.py**: 84.2100%
  **services.py**: 100%

### **profile**
  **forms.py**: 100%
  **models.py**: 76.9200%
  **repositories.py**: 100%
  **routes.py**: 76.6700%
  **services.py**: 100%

### **public**
  **routes.py**: 95.4500%

### **team**
  **routes.py**: 80.0%

### **webhook**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 0%
  **services.py**: 0%

### **zenodo**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 70.0%
  **services.py**: 35.8500%

**Comment by davidgonmar** [comment]
## Test Coverage Report
  **conftest.py**: 100%

### **auth**
  **forms.py**: 100%
  **models.py**: 88.6800%
  **repositories.py**: 88.2400%
  **routes.py**: 54.9800%
  **services.py**: 89.4400%

### **chatbot**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 48.00%
  **services.py**: 85.7100%

### **dataset**
  **api.py**: 100%
  **forms.py**: 78.00%
  **models.py**: 78.5200%
  **repositories.py**: 80.0%
  **routes.py**: 40.8400%
  **services.py**: 57.2400%

### **explore**
  **forms.py**: 100%
  **repositories.py**: 13.2700%
  **routes.py**: 77.7800%
  **services.py**: 100%

### **fakenodo**
  **forms.py**: 0%
  **models.py**: 70.0%
  **repositories.py**: 53.8500%
  **routes.py**: 35.2300%
  **services.py**: 81.8200%

### **featuremodel**
  **forms.py**: 0%
  **models.py**: 77.1900%
  **repositories.py**: 71.4300%
  **routes.py**: 94.4400%
  **services.py**: 96.4300%

### **flamapy**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 0%
  **routes.py**: 31.9400%
  **services.py**: 0%

### **hubfile**
  **forms.py**: 0%
  **models.py**: 73.9100%
  **repositories.py**: 92.3100%
  **routes.py**: 32.2600%
  **services.py**: 72.4100%

### **notepad**
  **forms.py**: 100%
  **models.py**: 88.8900%
  **repositories.py**: 100%
  **routes.py**: 84.2100%
  **services.py**: 100%

### **profile**
  **forms.py**: 100%
  **models.py**: 76.9200%
  **repositories.py**: 100%
  **routes.py**: 76.6700%
  **services.py**: 100%

### **public**
  **routes.py**: 95.4500%

### **team**
  **routes.py**: 80.0%

### **webhook**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 0%
  **services.py**: 0%

### **zenodo**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 70.0%
  **services.py**: 35.8500%

**Comment by davidgonmar** [comment]
## Test Coverage Report
  **conftest.py**: 100%

### **auth**
  **forms.py**: 100%
  **models.py**: 88.6800%
  **repositories.py**: 88.2400%
  **routes.py**: 54.9800%
  **services.py**: 89.4400%

### **chatbot**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 48.00%
  **services.py**: 85.7100%

### **dataset**
  **api.py**: 100%
  **forms.py**: 78.00%
  **models.py**: 78.5200%
  **repositories.py**: 80.0%
  **routes.py**: 40.900%
  **services.py**: 57.2400%

### **explore**
  **forms.py**: 100%
  **repositories.py**: 13.2700%
  **routes.py**: 75.00%
  **services.py**: 100%

### **fakenodo**
  **forms.py**: 0%
  **models.py**: 70.0%
  **repositories.py**: 53.8500%
  **routes.py**: 35.2300%
  **services.py**: 81.8200%

### **featuremodel**
  **forms.py**: 0%
  **models.py**: 77.1900%
  **repositories.py**: 71.4300%
  **routes.py**: 94.4400%
  **services.py**: 96.4300%

### **flamapy**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 0%
  **routes.py**: 31.9400%
  **services.py**: 0%

### **hubfile**
  **forms.py**: 0%
  **models.py**: 73.9100%
  **repositories.py**: 92.3100%
  **routes.py**: 32.2600%
  **services.py**: 72.4100%

### **notepad**
  **forms.py**: 100%
  **models.py**: 88.8900%
  **repositories.py**: 100%
  **routes.py**: 84.2100%
  **services.py**: 100%

### **profile**
  **forms.py**: 100%
  **models.py**: 76.9200%
  **repositories.py**: 100%
  **routes.py**: 76.6700%
  **services.py**: 100%

### **public**
  **routes.py**: 95.6500%

### **team**
  **routes.py**: 80.0%

### **webhook**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 0%
  **services.py**: 0%

### **zenodo**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 70.0%
  **services.py**: 35.8500%

**Comment by davidgonmar** [comment]
## Test Coverage Report
  **conftest.py**: 100%

### **auth**
  **forms.py**: 100%
  **models.py**: 88.6800%
  **repositories.py**: 88.2400%
  **routes.py**: 54.9800%
  **services.py**: 89.4400%

### **chatbot**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 48.00%
  **services.py**: 85.7100%

### **dataset**
  **api.py**: 100%
  **forms.py**: 78.00%
  **models.py**: 78.5200%
  **repositories.py**: 80.0%
  **routes.py**: 40.900%
  **services.py**: 57.2400%

### **explore**
  **forms.py**: 100%
  **repositories.py**: 13.2700%
  **routes.py**: 75.00%
  **services.py**: 100%

### **fakenodo**
  **forms.py**: 0%
  **models.py**: 70.0%
  **repositories.py**: 53.8500%
  **routes.py**: 35.2300%
  **services.py**: 81.8200%

### **featuremodel**
  **forms.py**: 0%
  **models.py**: 77.1900%
  **repositories.py**: 71.4300%
  **routes.py**: 94.4400%
  **services.py**: 96.4300%

### **flamapy**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 0%
  **routes.py**: 31.9400%
  **services.py**: 0%

### **hubfile**
  **forms.py**: 0%
  **models.py**: 73.9100%
  **repositories.py**: 92.3100%
  **routes.py**: 32.2600%
  **services.py**: 72.4100%

### **notepad**
  **forms.py**: 100%
  **models.py**: 88.8900%
  **repositories.py**: 100%
  **routes.py**: 84.2100%
  **services.py**: 100%

### **profile**
  **forms.py**: 100%
  **models.py**: 76.9200%
  **repositories.py**: 100%
  **routes.py**: 76.6700%
  **services.py**: 100%

### **public**
  **routes.py**: 95.6500%

### **team**
  **routes.py**: 80.0%

### **webhook**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 0%
  **services.py**: 0%

### **zenodo**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 70.0%
  **services.py**: 35.8500%

**Comment by davidgonmar** [comment]
## Test Coverage Report
  **conftest.py**: 100%

### **auth**
  **forms.py**: 100%
  **models.py**: 88.6800%
  **repositories.py**: 88.2400%
  **routes.py**: 54.9800%
  **services.py**: 89.4400%

### **chatbot**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 48.00%
  **services.py**: 85.7100%

### **dataset**
  **api.py**: 100%
  **forms.py**: 78.00%
  **models.py**: 78.5200%
  **repositories.py**: 80.0%
  **routes.py**: 40.900%
  **services.py**: 57.2400%

### **explore**
  **forms.py**: 100%
  **repositories.py**: 13.2700%
  **routes.py**: 75.00%
  **services.py**: 100%

### **fakenodo**
  **forms.py**: 0%
  **models.py**: 70.0%
  **repositories.py**: 53.8500%
  **routes.py**: 35.2300%
  **services.py**: 81.8200%

### **featuremodel**
  **forms.py**: 0%
  **models.py**: 77.1900%
  **repositories.py**: 71.4300%
  **routes.py**: 94.4400%
  **services.py**: 96.4300%

### **flamapy**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 0%
  **routes.py**: 31.9400%
  **services.py**: 0%

### **hubfile**
  **forms.py**: 0%
  **models.py**: 73.9100%
  **repositories.py**: 92.3100%
  **routes.py**: 32.2600%
  **services.py**: 72.4100%

### **notepad**
  **forms.py**: 100%
  **models.py**: 88.8900%
  **repositories.py**: 100%
  **routes.py**: 84.2100%
  **services.py**: 100%

### **profile**
  **forms.py**: 100%
  **models.py**: 76.9200%
  **repositories.py**: 100%
  **routes.py**: 76.6700%
  **services.py**: 100%

### **public**
  **routes.py**: 95.6500%

### **team**
  **routes.py**: 80.0%

### **webhook**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 0%
  **services.py**: 0%

### **zenodo**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 70.0%
  **services.py**: 35.8500%

**Review by adrvencon — APPROVED** [review]

**Comment by davidgonmar** [comment]
## Test Coverage Report
  **conftest.py**: 100%

### **auth**
  **forms.py**: 100%
  **models.py**: 88.6800%
  **repositories.py**: 88.2400%
  **routes.py**: 54.9800%
  **services.py**: 89.4400%

### **chatbot**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 48.00%
  **services.py**: 85.7100%

### **dataset**
  **api.py**: 100%
  **forms.py**: 78.00%
  **models.py**: 78.5200%
  **repositories.py**: 80.0%
  **routes.py**: 40.900%
  **services.py**: 57.2400%

### **explore**
  **forms.py**: 100%
  **repositories.py**: 13.2700%
  **routes.py**: 75.00%
  **services.py**: 100%

### **fakenodo**
  **forms.py**: 0%
  **models.py**: 70.0%
  **repositories.py**: 53.8500%
  **routes.py**: 35.2300%
  **services.py**: 81.8200%

### **featuremodel**
  **forms.py**: 0%
  **models.py**: 77.1900%
  **repositories.py**: 71.4300%
  **routes.py**: 94.4400%
  **services.py**: 96.4300%

### **flamapy**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 0%
  **routes.py**: 31.9400%
  **services.py**: 0%

### **hubfile**
  **forms.py**: 0%
  **models.py**: 73.9100%
  **repositories.py**: 92.3100%
  **routes.py**: 32.2600%
  **services.py**: 72.4100%

### **notepad**
  **forms.py**: 100%
  **models.py**: 88.8900%
  **repositories.py**: 100%
  **routes.py**: 84.2100%
  **services.py**: 100%

### **profile**
  **forms.py**: 100%
  **models.py**: 76.9200%
  **repositories.py**: 100%
  **routes.py**: 76.6700%
  **services.py**: 100%

### **public**
  **routes.py**: 95.6500%

### **team**
  **routes.py**: 80.0%

### **webhook**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 0%
  **services.py**: 0%

### **zenodo**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 70.0%
  **services.py**: 35.8500%

**Pull request merged**
