### PR TITLE
g1/task_3/receive_and_validate_input_code

### PR DESCRIPTION
**Pull request by davidgonmar**
Connects previous work so the sign up email verification is done correctly.
Closes https://github.com/davidgonmar/uvlhub-egc/issues/7

### CODE REVIEW

**Comment by davidgonmar** [comment]
## Test Coverage Report
  **conftest.py**: 100%

### **auth**
  **forms.py**: 100%
  **models.py**: 87.100%
  **repositories.py**: 90.0%
  **routes.py**: 44.2500%
  **services.py**: 62.7700%

### **chatbot**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 80.0%
  **services.py**: 0%

### **dataset**
  **api.py**: 100%
  **forms.py**: 78.00%
  **models.py**: 82.6900%
  **repositories.py**: 84.6200%
  **routes.py**: 27.7800%
  **services.py**: 48.9200%

### **explore**
  **forms.py**: 100%
  **repositories.py**: 22.500%
  **routes.py**: 42.8600%
  **services.py**: 71.4300%

### **featuremodel**
  **forms.py**: 0%
  **models.py**: 90.3200%
  **repositories.py**: 100%
  **routes.py**: 80.0%
  **services.py**: 93.7500%

### **flamapy**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 0%
  **routes.py**: 31.9400%
  **services.py**: 0%

### **hubfile**
  **forms.py**: 0%
  **models.py**: 73.9100%
  **repositories.py**: 92.3100%
  **routes.py**: 25.00%
  **services.py**: 72.4100%

### **notepad**
  **forms.py**: 100%
  **models.py**: 88.8900%
  **repositories.py**: 100%
  **routes.py**: 84.2100%
  **services.py**: 100%

### **profile**
  **forms.py**: 100%
  **models.py**: 75.00%
  **repositories.py**: 100%
  **routes.py**: 66.6700%
  **services.py**: 60.0%

### **public**
  **routes.py**: 100%

### **team**
  **routes.py**: 80.0%

### **webhook**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 0%
  **services.py**: 0%

### **zenodo**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 70.0%
  **services.py**: 35.2400%

**Comment by davidgonmar** [comment]
## Test Coverage Report
  **conftest.py**: 100%

### **auth**
  **forms.py**: 100%
  **models.py**: 87.100%
  **repositories.py**: 90.0%
  **routes.py**: 43.7500%
  **services.py**: 64.1300%

### **chatbot**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 80.0%
  **services.py**: 0%

### **dataset**
  **api.py**: 100%
  **forms.py**: 78.00%
  **models.py**: 82.6900%
  **repositories.py**: 84.6200%
  **routes.py**: 27.7800%
  **services.py**: 48.9200%

### **explore**
  **forms.py**: 100%
  **repositories.py**: 22.500%
  **routes.py**: 42.8600%
  **services.py**: 71.4300%

### **featuremodel**
  **forms.py**: 0%
  **models.py**: 90.3200%
  **repositories.py**: 100%
  **routes.py**: 80.0%
  **services.py**: 93.7500%

### **flamapy**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 0%
  **routes.py**: 31.9400%
  **services.py**: 0%

### **hubfile**
  **forms.py**: 0%
  **models.py**: 73.9100%
  **repositories.py**: 92.3100%
  **routes.py**: 25.00%
  **services.py**: 72.4100%

### **notepad**
  **forms.py**: 100%
  **models.py**: 88.8900%
  **repositories.py**: 100%
  **routes.py**: 84.2100%
  **services.py**: 100%

### **profile**
  **forms.py**: 100%
  **models.py**: 75.00%
  **repositories.py**: 100%
  **routes.py**: 66.6700%
  **services.py**: 60.0%

### **public**
  **routes.py**: 100%

### **team**
  **routes.py**: 80.0%

### **webhook**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 0%
  **services.py**: 0%

### **zenodo**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 70.0%
  **services.py**: 35.2400%

**Comment by davidgonmar** [comment]
## Test Coverage Report
  **conftest.py**: 100%

### **auth**
  **forms.py**: 100%
  **models.py**: 87.100%
  **repositories.py**: 90.0%
  **routes.py**: 44.2500%
  **services.py**: 65.3800%

### **chatbot**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 80.0%
  **services.py**: 0%

### **dataset**
  **api.py**: 100%
  **forms.py**: 78.00%
  **models.py**: 82.6900%
  **repositories.py**: 84.6200%
  **routes.py**: 27.7800%
  **services.py**: 48.9200%

### **explore**
  **forms.py**: 100%
  **repositories.py**: 22.500%
  **routes.py**: 42.8600%
  **services.py**: 71.4300%

### **featuremodel**
  **forms.py**: 0%
  **models.py**: 90.3200%
  **repositories.py**: 100%
  **routes.py**: 80.0%
  **services.py**: 93.7500%

### **flamapy**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 0%
  **routes.py**: 31.9400%
  **services.py**: 0%

### **hubfile**
  **forms.py**: 0%
  **models.py**: 73.9100%
  **repositories.py**: 92.3100%
  **routes.py**: 25.00%
  **services.py**: 72.4100%

### **notepad**
  **forms.py**: 100%
  **models.py**: 88.8900%
  **repositories.py**: 100%
  **routes.py**: 84.2100%
  **services.py**: 100%

### **profile**
  **forms.py**: 100%
  **models.py**: 75.00%
  **repositories.py**: 100%
  **routes.py**: 66.6700%
  **services.py**: 60.0%

### **public**
  **routes.py**: 100%

### **team**
  **routes.py**: 80.0%

### **webhook**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 0%
  **services.py**: 0%

### **zenodo**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 70.0%
  **services.py**: 35.2400%

**Review by rafcasceb — APPROVED** [review]
Perfecto.

**Pull request merged**
