### PR TITLE
Final documentation changes for G2.

### PR DESCRIPTION
**Pull request by adrvencon**
### **PR Type**
Documentation

___

### **Description**
- Created comprehensive pipeline documentation detailing CI/CD workflows, local hooks, and deployment processes
- Restructured and updated foundational document with improved organization and additional sections
- Added final team meeting record documenting project closure and last agreements
- Improved documentation structure by adding repository and deployment links at the top of documents
- Updated issue management guidelines and labels in foundational document

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>Acta_fundacional-G2.md</strong><dd><code>Restructure and update of foundational document</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

documentation/g2/Acta_fundacional-G2.md

<li>Reorganized document structure and updated section numbering<br> <li> Added links to repository and deployed system at the top<br> <li> Updated issue labels and types section<br> <li> Added note about bot-generated issues<br>

</details>

  </td>
  <td><a href="https://github.com/davidgonmar/uvlhub-egc/pull/206/files#diff-75c06cd3c8e04f6c7f2857b0550d6ab110f5aff7c49c1c67461ca9296f7cb549">+19/-32</a>&nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>Diario_del_equipo-G2.md</strong><dd><code>Add final team meeting and update document structure</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

documentation/g2/Diario_del_equipo-G2.md

<li>Added links to repository and deployed system at the top<br> <li> Updated meeting statistics and counts<br> <li> Added new meeting record (ACTA 2024-05) documenting project closure<br>

</details>

  </td>
  <td><a href="https://github.com/davidgonmar/uvlhub-egc/pull/206/files#diff-99dbda4f7561ee91cd0f8229f1f6c50bc316b3feb6dccb5eb6af59d39ebee1d3">+32/-10</a>&nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>Pipeline_del_Repositorio.md</strong><dd><code>New documentation for repository pipeline and workflows</code>&nbsp; &nbsp; </dd></summary>
<hr>

documentation/g2/Pipeline_del_Repositorio.md

<li>Created new document describing the repository's CI/CD pipeline<br> <li> Detailed workflow stages, hooks, and automation processes<br> <li> Added pipeline diagram and benefits section<br>

</details>

  </td>
  <td><a href="https://github.com/davidgonmar/uvlhub-egc/pull/206/files#diff-4e5dbcd74dad5d0e7d0cacaad6942c96a29e2d68127424c37951c9b55cc825d3">+120/-0</a>&nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by davidgonmar** [comment]
## Test Coverage Report
  **conftest.py**: 100%

### **auth**
  **forms.py**: 100%
  **models.py**: 88.6800%
  **repositories.py**: 84.3100%
  **routes.py**: 53.7800%
  **services.py**: 71.1100%

### **chatbot**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 48.00%
  **services.py**: 85.7100%

### **dataset**
  **api.py**: 100%
  **forms.py**: 78.00%
  **models.py**: 78.5200%
  **repositories.py**: 80.0%
  **routes.py**: 43.1400%
  **services.py**: 57.2400%

### **explore**
  **forms.py**: 100%
  **repositories.py**: 13.2700%
  **routes.py**: 77.7800%
  **services.py**: 100%

### **fakenodo**
  **forms.py**: 0%
  **models.py**: 70.0%
  **repositories.py**: 53.8500%
  **routes.py**: 35.2300%
  **services.py**: 81.8200%

### **featuremodel**
  **forms.py**: 0%
  **models.py**: 77.1900%
  **repositories.py**: 71.4300%
  **routes.py**: 94.4400%
  **services.py**: 96.4300%

### **flamapy**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 0%
  **routes.py**: 31.9400%
  **services.py**: 0%

### **hubfile**
  **forms.py**: 0%
  **models.py**: 73.9100%
  **repositories.py**: 92.3100%
  **routes.py**: 32.2600%
  **services.py**: 72.4100%

### **notepad**
  **forms.py**: 100%
  **models.py**: 88.8900%
  **repositories.py**: 100%
  **routes.py**: 84.2100%
  **services.py**: 100%

### **profile**
  **forms.py**: 100%
  **models.py**: 76.9200%
  **repositories.py**: 100%
  **routes.py**: 76.6700%
  **services.py**: 100%

### **public**
  **routes.py**: 95.4500%

### **team**
  **routes.py**: 80.0%

### **webhook**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 0%
  **services.py**: 0%

### **zenodo**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 70.0%
  **services.py**: 35.8500%

**Comment by davidgonmar** [comment]
## Test Coverage Report
  **conftest.py**: 100%

### **auth**
  **forms.py**: 100%
  **models.py**: 88.6800%
  **repositories.py**: 84.3100%
  **routes.py**: 53.7800%
  **services.py**: 71.1100%

### **chatbot**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 48.00%
  **services.py**: 85.7100%

### **dataset**
  **api.py**: 100%
  **forms.py**: 78.00%
  **models.py**: 78.5200%
  **repositories.py**: 80.0%
  **routes.py**: 43.1400%
  **services.py**: 57.2400%

### **explore**
  **forms.py**: 100%
  **repositories.py**: 13.2700%
  **routes.py**: 77.7800%
  **services.py**: 100%

### **fakenodo**
  **forms.py**: 0%
  **models.py**: 70.0%
  **repositories.py**: 53.8500%
  **routes.py**: 35.2300%
  **services.py**: 81.8200%

### **featuremodel**
  **forms.py**: 0%
  **models.py**: 77.1900%
  **repositories.py**: 71.4300%
  **routes.py**: 94.4400%
  **services.py**: 96.4300%

### **flamapy**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 0%
  **routes.py**: 31.9400%
  **services.py**: 0%

### **hubfile**
  **forms.py**: 0%
  **models.py**: 73.9100%
  **repositories.py**: 92.3100%
  **routes.py**: 32.2600%
  **services.py**: 72.4100%

### **notepad**
  **forms.py**: 100%
  **models.py**: 88.8900%
  **repositories.py**: 100%
  **routes.py**: 84.2100%
  **services.py**: 100%

### **profile**
  **forms.py**: 100%
  **models.py**: 76.9200%
  **repositories.py**: 100%
  **routes.py**: 76.6700%
  **services.py**: 100%

### **public**
  **routes.py**: 95.4500%

### **team**
  **routes.py**: 80.0%

### **webhook**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 0%
  **services.py**: 0%

### **zenodo**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 70.0%
  **services.py**: 35.8500%

**Comment by davidgonmar** [comment]
## Test Coverage Report
  **conftest.py**: 100%

### **auth**
  **forms.py**: 100%
  **models.py**: 88.6800%
  **repositories.py**: 88.2400%
  **routes.py**: 54.9800%
  **services.py**: 89.4400%

### **chatbot**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 48.00%
  **services.py**: 85.7100%

### **dataset**
  **api.py**: 100%
  **forms.py**: 78.00%
  **models.py**: 78.5200%
  **repositories.py**: 80.0%
  **routes.py**: 40.900%
  **services.py**: 57.2400%

### **explore**
  **forms.py**: 100%
  **repositories.py**: 13.2700%
  **routes.py**: 75.00%
  **services.py**: 100%

### **fakenodo**
  **forms.py**: 0%
  **models.py**: 70.0%
  **repositories.py**: 53.8500%
  **routes.py**: 35.2300%
  **services.py**: 81.8200%

### **featuremodel**
  **forms.py**: 0%
  **models.py**: 77.1900%
  **repositories.py**: 71.4300%
  **routes.py**: 94.4400%
  **services.py**: 96.4300%

### **flamapy**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 0%
  **routes.py**: 31.9400%
  **services.py**: 0%

### **hubfile**
  **forms.py**: 0%
  **models.py**: 73.9100%
  **repositories.py**: 92.3100%
  **routes.py**: 32.2600%
  **services.py**: 72.4100%

### **notepad**
  **forms.py**: 100%
  **models.py**: 88.8900%
  **repositories.py**: 100%
  **routes.py**: 84.2100%
  **services.py**: 100%

### **profile**
  **forms.py**: 100%
  **models.py**: 76.9200%
  **repositories.py**: 100%
  **routes.py**: 76.6700%
  **services.py**: 100%

### **public**
  **routes.py**: 95.6500%

### **team**
  **routes.py**: 80.0%

### **webhook**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 0%
  **services.py**: 0%

### **zenodo**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 70.0%
  **services.py**: 35.8500%

**Comment by davidgonmar** [comment]
## Test Coverage Report
  **conftest.py**: 100%

### **auth**
  **forms.py**: 100%
  **models.py**: 88.6800%
  **repositories.py**: 88.2400%
  **routes.py**: 54.9800%
  **services.py**: 89.4400%

### **chatbot**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 48.00%
  **services.py**: 85.7100%

### **dataset**
  **api.py**: 100%
  **forms.py**: 78.00%
  **models.py**: 78.5200%
  **repositories.py**: 80.0%
  **routes.py**: 40.900%
  **services.py**: 57.2400%

### **explore**
  **forms.py**: 100%
  **repositories.py**: 13.2700%
  **routes.py**: 75.00%
  **services.py**: 100%

### **fakenodo**
  **forms.py**: 0%
  **models.py**: 70.0%
  **repositories.py**: 53.8500%
  **routes.py**: 35.2300%
  **services.py**: 81.8200%

### **featuremodel**
  **forms.py**: 0%
  **models.py**: 77.1900%
  **repositories.py**: 71.4300%
  **routes.py**: 94.4400%
  **services.py**: 96.4300%

### **flamapy**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 0%
  **routes.py**: 31.9400%
  **services.py**: 0%

### **hubfile**
  **forms.py**: 0%
  **models.py**: 73.9100%
  **repositories.py**: 92.3100%
  **routes.py**: 32.2600%
  **services.py**: 72.4100%

### **notepad**
  **forms.py**: 100%
  **models.py**: 88.8900%
  **repositories.py**: 100%
  **routes.py**: 84.2100%
  **services.py**: 100%

### **profile**
  **forms.py**: 100%
  **models.py**: 76.9200%
  **repositories.py**: 100%
  **routes.py**: 76.6700%
  **services.py**: 100%

### **public**
  **routes.py**: 95.6500%

### **team**
  **routes.py**: 80.0%

### **webhook**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 0%
  **services.py**: 0%

### **zenodo**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 70.0%
  **services.py**: 35.8500%

**Comment by davidgonmar** [comment]
## Test Coverage Report
  **conftest.py**: 100%

### **auth**
  **forms.py**: 100%
  **models.py**: 88.6800%
  **repositories.py**: 88.2400%
  **routes.py**: 54.9800%
  **services.py**: 91.1200%

### **chatbot**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 48.00%
  **services.py**: 85.7100%

### **dataset**
  **api.py**: 100%
  **forms.py**: 78.00%
  **models.py**: 78.5200%
  **repositories.py**: 80.0%
  **routes.py**: 40.900%
  **services.py**: 57.2400%

### **explore**
  **forms.py**: 100%
  **repositories.py**: 14.2900%
  **routes.py**: 75.00%
  **services.py**: 100%

### **fakenodo**
  **forms.py**: 0%
  **models.py**: 70.0%
  **repositories.py**: 53.8500%
  **routes.py**: 35.2300%
  **services.py**: 81.8200%

### **featuremodel**
  **forms.py**: 0%
  **models.py**: 77.1900%
  **repositories.py**: 71.4300%
  **routes.py**: 94.4400%
  **services.py**: 96.4300%

### **flamapy**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 0%
  **routes.py**: 31.9400%
  **services.py**: 0%

### **hubfile**
  **forms.py**: 0%
  **models.py**: 73.9100%
  **repositories.py**: 92.3100%
  **routes.py**: 32.2600%
  **services.py**: 72.4100%

### **notepad**
  **forms.py**: 100%
  **models.py**: 88.8900%
  **repositories.py**: 100%
  **routes.py**: 84.2100%
  **services.py**: 100%

### **profile**
  **forms.py**: 100%
  **models.py**: 76.9200%
  **repositories.py**: 100%
  **routes.py**: 76.6700%
  **services.py**: 100%

### **public**
  **routes.py**: 95.6500%

### **team**
  **routes.py**: 80.0%

### **webhook**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 0%
  **services.py**: 0%

### **zenodo**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 70.0%
  **services.py**: 35.8500%

**Comment by davidgonmar** [comment]
## Test Coverage Report
  **conftest.py**: 100%

### **auth**
  **forms.py**: 100%
  **models.py**: 88.6800%
  **repositories.py**: 88.2400%
  **routes.py**: 54.9800%
  **services.py**: 91.1200%

### **chatbot**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 48.00%
  **services.py**: 85.7100%

### **dataset**
  **api.py**: 100%
  **forms.py**: 78.00%
  **models.py**: 78.5200%
  **repositories.py**: 80.0%
  **routes.py**: 40.900%
  **services.py**: 57.2400%

### **explore**
  **forms.py**: 100%
  **repositories.py**: 14.2900%
  **routes.py**: 75.00%
  **services.py**: 100%

### **fakenodo**
  **forms.py**: 0%
  **models.py**: 70.0%
  **repositories.py**: 53.8500%
  **routes.py**: 35.2300%
  **services.py**: 81.8200%

### **featuremodel**
  **forms.py**: 0%
  **models.py**: 77.1900%
  **repositories.py**: 71.4300%
  **routes.py**: 94.4400%
  **services.py**: 96.4300%

### **flamapy**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 0%
  **routes.py**: 31.9400%
  **services.py**: 0%

### **hubfile**
  **forms.py**: 0%
  **models.py**: 73.9100%
  **repositories.py**: 92.3100%
  **routes.py**: 32.2600%
  **services.py**: 72.4100%

### **notepad**
  **forms.py**: 100%
  **models.py**: 88.8900%
  **repositories.py**: 100%
  **routes.py**: 84.2100%
  **services.py**: 100%

### **profile**
  **forms.py**: 100%
  **models.py**: 76.9200%
  **repositories.py**: 100%
  **routes.py**: 76.6700%
  **services.py**: 100%

### **public**
  **routes.py**: 95.6500%

### **team**
  **routes.py**: 80.0%

### **webhook**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 0%
  **services.py**: 0%

### **zenodo**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 70.0%
  **services.py**: 35.8500%

**Comment by davidgonmar** [comment]
## Test Coverage Report
  **conftest.py**: 100%

### **auth**
  **forms.py**: 100%
  **models.py**: 88.6800%
  **repositories.py**: 88.2400%
  **routes.py**: 54.9800%
  **services.py**: 91.1200%

### **chatbot**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 48.00%
  **services.py**: 85.7100%

### **dataset**
  **api.py**: 100%
  **forms.py**: 78.00%
  **models.py**: 78.5200%
  **repositories.py**: 80.0%
  **routes.py**: 40.900%
  **services.py**: 57.2400%

### **explore**
  **forms.py**: 100%
  **repositories.py**: 14.2900%
  **routes.py**: 75.00%
  **services.py**: 100%

### **fakenodo**
  **forms.py**: 0%
  **models.py**: 70.0%
  **repositories.py**: 53.8500%
  **routes.py**: 35.2300%
  **services.py**: 81.8200%

### **featuremodel**
  **forms.py**: 0%
  **models.py**: 77.1900%
  **repositories.py**: 71.4300%
  **routes.py**: 94.4400%
  **services.py**: 96.4300%

### **flamapy**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 0%
  **routes.py**: 31.9400%
  **services.py**: 0%

### **hubfile**
  **forms.py**: 0%
  **models.py**: 73.9100%
  **repositories.py**: 92.3100%
  **routes.py**: 32.2600%
  **services.py**: 72.4100%

### **notepad**
  **forms.py**: 100%
  **models.py**: 88.8900%
  **repositories.py**: 100%
  **routes.py**: 84.2100%
  **services.py**: 100%

### **profile**
  **forms.py**: 100%
  **models.py**: 76.9200%
  **repositories.py**: 100%
  **routes.py**: 76.6700%
  **services.py**: 100%

### **public**
  **routes.py**: 95.6500%

### **team**
  **routes.py**: 80.0%

### **webhook**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 0%
  **services.py**: 0%

### **zenodo**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 70.0%
  **services.py**: 35.8500%

**Comment by davidgonmar** [comment]
## Test Coverage Report
  **conftest.py**: 100%

### **auth**
  **forms.py**: 100%
  **models.py**: 88.6800%
  **repositories.py**: 88.2400%
  **routes.py**: 54.9800%
  **services.py**: 91.1200%

### **chatbot**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 48.00%
  **services.py**: 85.7100%

### **dataset**
  **api.py**: 100%
  **forms.py**: 78.00%
  **models.py**: 78.5200%
  **repositories.py**: 80.0%
  **routes.py**: 40.900%
  **services.py**: 57.2400%

### **explore**
  **forms.py**: 100%
  **repositories.py**: 14.2900%
  **routes.py**: 75.00%
  **services.py**: 100%

### **fakenodo**
  **forms.py**: 0%
  **models.py**: 70.0%
  **repositories.py**: 53.8500%
  **routes.py**: 35.2300%
  **services.py**: 81.8200%

### **featuremodel**
  **forms.py**: 0%
  **models.py**: 77.1900%
  **repositories.py**: 71.4300%
  **routes.py**: 94.4400%
  **services.py**: 96.4300%

### **flamapy**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 0%
  **routes.py**: 31.9400%
  **services.py**: 0%

### **hubfile**
  **forms.py**: 0%
  **models.py**: 73.9100%
  **repositories.py**: 92.3100%
  **routes.py**: 32.2600%
  **services.py**: 72.4100%

### **notepad**
  **forms.py**: 100%
  **models.py**: 88.8900%
  **repositories.py**: 100%
  **routes.py**: 84.2100%
  **services.py**: 100%

### **profile**
  **forms.py**: 100%
  **models.py**: 76.9200%
  **repositories.py**: 100%
  **routes.py**: 76.6700%
  **services.py**: 100%

### **public**
  **routes.py**: 95.6500%

### **team**
  **routes.py**: 80.0%

### **webhook**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 0%
  **services.py**: 0%

### **zenodo**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 70.0%
  **services.py**: 35.8500%

**Comment by davidgonmar** [comment]
## Test Coverage Report
  **conftest.py**: 100%

### **auth**
  **forms.py**: 100%
  **models.py**: 88.6800%
  **repositories.py**: 88.2400%
  **routes.py**: 54.9800%
  **services.py**: 91.1200%

### **chatbot**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 48.00%
  **services.py**: 85.7100%

### **dataset**
  **api.py**: 100%
  **forms.py**: 78.00%
  **models.py**: 78.5200%
  **repositories.py**: 80.0%
  **routes.py**: 40.900%
  **services.py**: 57.2400%

### **explore**
  **forms.py**: 100%
  **repositories.py**: 14.2900%
  **routes.py**: 75.00%
  **services.py**: 100%

### **fakenodo**
  **forms.py**: 0%
  **models.py**: 70.0%
  **repositories.py**: 53.8500%
  **routes.py**: 35.2300%
  **services.py**: 81.8200%

### **featuremodel**
  **forms.py**: 0%
  **models.py**: 77.1900%
  **repositories.py**: 71.4300%
  **routes.py**: 94.4400%
  **services.py**: 96.4300%

### **flamapy**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 0%
  **routes.py**: 31.9400%
  **services.py**: 0%

### **hubfile**
  **forms.py**: 0%
  **models.py**: 73.9100%
  **repositories.py**: 92.3100%
  **routes.py**: 32.2600%
  **services.py**: 72.4100%

### **notepad**
  **forms.py**: 100%
  **models.py**: 88.8900%
  **repositories.py**: 100%
  **routes.py**: 84.2100%
  **services.py**: 100%

### **profile**
  **forms.py**: 100%
  **models.py**: 76.9200%
  **repositories.py**: 100%
  **routes.py**: 76.6700%
  **services.py**: 100%

### **public**
  **routes.py**: 95.6500%

### **team**
  **routes.py**: 80.0%

### **webhook**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 0%
  **services.py**: 0%

### **zenodo**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 70.0%
  **services.py**: 35.8500%

**Review by Cargarmar18 — APPROVED** [review]

**Pull request merged**
