### PR TITLE
Tests for Multiple Login

### LINKED ISSUE #67: Tarea 21: Write tests - Multiple Login
Work item:

> Multiple login

Description:

> + Write unit tests for multiple login.
> + Unit tests are compulsory. Load and Selenium tests should be done if possible, but there may be WI which don't support them. If they are possible, we must do them.

### PR DESCRIPTION
**Pull request by Sergiotg03**
### **User description**
Closes #67

___

### **PR Type**
Tests

___

### **Description**
Added comprehensive unit tests for multiple social login authentication providers:

ORCID Tests:
- OAuth configuration and setup validation
- Full profile retrieval functionality
- Login and authorization routes testing

Google Tests:
- User creation and profile association
- Handling of existing users
- Data validation and error cases
- Login redirect verification

GitHub Tests:
- User creation with complete and default values
- Handling missing email scenarios
- Duplicate GitHub ID validation
- Login redirect functionality

All tests ensure proper:
- Database interactions
- User profile creation
- Data validation
- Error handling

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>test_unit.py</strong><dd><code>Unit Tests for Multiple Social Login Authentication</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

app/modules/auth/tests/test_unit.py

<li>Added ORCID authentication tests: OAuth configuration, profile <br>retrieval, and login routes<br> <li> Added Google authentication tests: user creation, data validation, and <br>login redirect<br> <li> Added GitHub authentication tests: user creation with various <br>scenarios and login redirect<br> <li> All tests cover both successful and error cases for each <br>authentication provider<br>

</details>

  </td>
  <td><a href="https://github.com/davidgonmar/uvlhub-egc/pull/207/files#diff-8962a795efc9c990b985f29e4dc0ea3642312b841956bd7b782e426a88c29386">+244/-1</a>&nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by davidgonmar** [comment]
## Test Coverage Report
  **conftest.py**: 100%

### **auth**
  **forms.py**: 100%
  **models.py**: 88.6800%
  **repositories.py**: 88.2400%
  **routes.py**: 54.9800%
  **services.py**: 89.4400%

### **chatbot**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 48.00%
  **services.py**: 85.7100%

### **dataset**
  **api.py**: 100%
  **forms.py**: 78.00%
  **models.py**: 78.5200%
  **repositories.py**: 80.0%
  **routes.py**: 40.8500%
  **services.py**: 55.2600%

### **explore**
  **forms.py**: 100%
  **repositories.py**: 13.2700%
  **routes.py**: 77.7800%
  **services.py**: 100%

### **fakenodo**
  **forms.py**: 0%
  **models.py**: 70.0%
  **repositories.py**: 53.8500%
  **routes.py**: 35.2300%
  **services.py**: 81.8200%

### **featuremodel**
  **forms.py**: 0%
  **models.py**: 77.1900%
  **repositories.py**: 71.4300%
  **routes.py**: 55.5600%
  **services.py**: 85.7100%

### **flamapy**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 0%
  **routes.py**: 31.9400%
  **services.py**: 0%

### **hubfile**
  **forms.py**: 0%
  **models.py**: 73.9100%
  **repositories.py**: 92.3100%
  **routes.py**: 32.2600%
  **services.py**: 72.4100%

### **notepad**
  **forms.py**: 100%
  **models.py**: 88.8900%
  **repositories.py**: 100%
  **routes.py**: 84.2100%
  **services.py**: 100%

### **profile**
  **forms.py**: 100%
  **models.py**: 76.9200%
  **repositories.py**: 100%
  **routes.py**: 76.6700%
  **services.py**: 100%

### **public**
  **routes.py**: 95.4500%

### **team**
  **routes.py**: 80.0%

### **webhook**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 0%
  **services.py**: 0%

### **zenodo**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 70.0%
  **services.py**: 35.8500%

**Comment by davidgonmar** [comment]
## Test Coverage Report
  **conftest.py**: 100%

### **auth**
  **forms.py**: 100%
  **models.py**: 88.6800%
  **repositories.py**: 88.2400%
  **routes.py**: 54.9800%
  **services.py**: 89.4400%

### **chatbot**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 48.00%
  **services.py**: 85.7100%

### **dataset**
  **api.py**: 100%
  **forms.py**: 78.00%
  **models.py**: 78.5200%
  **repositories.py**: 80.0%
  **routes.py**: 40.8500%
  **services.py**: 55.2600%

### **explore**
  **forms.py**: 100%
  **repositories.py**: 13.2700%
  **routes.py**: 77.7800%
  **services.py**: 100%

### **fakenodo**
  **forms.py**: 0%
  **models.py**: 70.0%
  **repositories.py**: 53.8500%
  **routes.py**: 35.2300%
  **services.py**: 81.8200%

### **featuremodel**
  **forms.py**: 0%
  **models.py**: 77.1900%
  **repositories.py**: 71.4300%
  **routes.py**: 55.5600%
  **services.py**: 85.7100%

### **flamapy**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 0%
  **routes.py**: 31.9400%
  **services.py**: 0%

### **hubfile**
  **forms.py**: 0%
  **models.py**: 73.9100%
  **repositories.py**: 92.3100%
  **routes.py**: 32.2600%
  **services.py**: 72.4100%

### **notepad**
  **forms.py**: 100%
  **models.py**: 88.8900%
  **repositories.py**: 100%
  **routes.py**: 84.2100%
  **services.py**: 100%

### **profile**
  **forms.py**: 100%
  **models.py**: 76.9200%
  **repositories.py**: 100%
  **routes.py**: 76.6700%
  **services.py**: 100%

### **public**
  **routes.py**: 95.4500%

### **team**
  **routes.py**: 80.0%

### **webhook**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 0%
  **services.py**: 0%

### **zenodo**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 70.0%
  **services.py**: 35.8500%

**Comment by davidgonmar** [comment]
## Test Coverage Report
  **conftest.py**: 100%

### **auth**
  **forms.py**: 100%
  **models.py**: 88.6800%
  **repositories.py**: 88.2400%
  **routes.py**: 54.9800%
  **services.py**: 89.4400%

### **chatbot**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 48.00%
  **services.py**: 85.7100%

### **dataset**
  **api.py**: 100%
  **forms.py**: 78.00%
  **models.py**: 78.5200%
  **repositories.py**: 80.0%
  **routes.py**: 43.1400%
  **services.py**: 57.2400%

### **explore**
  **forms.py**: 100%
  **repositories.py**: 13.2700%
  **routes.py**: 77.7800%
  **services.py**: 100%

### **fakenodo**
  **forms.py**: 0%
  **models.py**: 70.0%
  **repositories.py**: 53.8500%
  **routes.py**: 35.2300%
  **services.py**: 81.8200%

### **featuremodel**
  **forms.py**: 0%
  **models.py**: 77.1900%
  **repositories.py**: 71.4300%
  **routes.py**: 94.4400%
  **services.py**: 96.4300%

### **flamapy**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 0%
  **routes.py**: 31.9400%
  **services.py**: 0%

### **hubfile**
  **forms.py**: 0%
  **models.py**: 73.9100%
  **repositories.py**: 92.3100%
  **routes.py**: 32.2600%
  **services.py**: 72.4100%

### **notepad**
  **forms.py**: 100%
  **models.py**: 88.8900%
  **repositories.py**: 100%
  **routes.py**: 84.2100%
  **services.py**: 100%

### **profile**
  **forms.py**: 100%
  **models.py**: 76.9200%
  **repositories.py**: 100%
  **routes.py**: 76.6700%
  **services.py**: 100%

### **public**
  **routes.py**: 95.4500%

### **team**
  **routes.py**: 80.0%

### **webhook**
  **forms.py**: 0%
  **models.py**: 0%
  **repositories.py**: 0%
  **routes.py**: 0%
  **services.py**: 0%

### **zenodo**
  **forms.py**: 0%
  **models.py**: 100%
  **repositories.py**: 100%
  **routes.py**: 70.0%
  **services.py**: 35.8500%

**Review by raulherasperez — COMMENTED** [review]
Los tests funcionan correctamente.

**Pull request merged**
